apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: health
type: Opaque
stringData:
  database-url: postgresql+psycopg://postgres:postgres@postgres:5432/health
  secret-key: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: health
type: Opaque
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secrets
  namespace: health
type: Opaque
stringData:
  admin-password: change-me-strong-password
